apiVersion: v1
kind: Namespace
metadata:
  name: checks-openshift
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checks-openshift
  namespace: checks-openshift
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: checks-openshift
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: checks-openshift
    namespace: checks-openshift
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: openshift-checks-py
  namespace: checks-openshift
spec:
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: openshift-checks-py
              image: quay.io/loganmc10/openshift-checks-py:latest
              imagePullPolicy: Always
              args: ["--incluster-config", "--no-colors"]
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
          serviceAccountName: checks-openshift
          restartPolicy: Never
  schedule: "47 4 * * *"
