name: Build project
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-code:
    runs-on: ubuntu-latest
    container: registry.access.redhat.com/ubi9/ubi:latest
    steps:
      - uses: actions/checkout@v3
      - name: Check code
        run: |
          dnf -y update
          dnf -y install python3-pip binutils
          pip3 install -r requirements.txt
          pip3 install flake8 black mypy bandit types-tabulate types-requests types-python-dateutil types-PyYAML
          flake8 --ignore E501,W503 .
          mypy --strict .
          bandit -r .
          black --check .
  build-binary:
    runs-on: ubuntu-latest
    container: registry.access.redhat.com/ubi9/ubi:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build binary
        run: |
          dnf -y update
          dnf -y install python3-pip binutils gcc zlib-devel
          pip3 install wheel
          pip3 install -r requirements.txt
          pip3 install pyinstaller
          pyinstaller -F ./openshift-checks.py
          mv dist/openshift-checks openshift-checks
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: openshift-checks
          path: openshift-checks
